gen2_root: /data/des90.a/data/neilsen/DC2/repoRun2.2i
gen3_root:  /data/des90.a/data/neilsen/DC2gen3
instrument: lsst.obs.lsst.LsstImSim
delete_old_gen3: True
create_new_gen3: True
convertRepo_config: convertrepo.pexconfig 
butler_seed: butler_seed.yaml
reruns:
    - path: rerun/w_2020_28/DM-25915/sfm
      runName: w_2020_28/DM-25915/sfm
      chainName: null
      parents: []
visits: null
calibs:
    CALIB: calib
convert_skymap: False
